resolver: lts-7.0
packages:
  - '.'
  - location:
      git: https://github.com/sopvop/jsonapi-typed.git
      commit: a1239b5df38a2a0bce4f913e7d26873bb3d9169c
extra-deps:
  - heist-1.0.0.0
  - jose-0.5.0.0
  - jsonapi-typed-0.1.0.0
  - map-syntax-0.2.0.1
  - servant-snap-0.7.0.2
  - snap-1.0.0.0
  - snap-loader-static-1.0.0.0
  - snap-loader-dynamic-1.0.0.0
  - snaplet-postgresql-simple-1.0.1.0
  - uuid-aeson-0.1.0.0

flags: {}
extra-package-dbs: []
extra-include-dirs: []
extra-lib-dirs: []
# compiler-check: newer-minor # Allow a newer minor version of GHC
